### ISSUE TITLE
Reviewer flow

### ISSUE THREAD

**Issue by sofiatti** [computablelabs/dapp-universities#10]
**As a** person going through the demo, **I want** to go through the reviewer flow **so that** I can understand how voting happens.

### Acceptance Criteria
- [x] When a user clicks the button `reviewer` in #3, a page should load with all the listing candidates from the last 3 minutes (actual time TBD) 
- [x] That page should have a challenge button. 
- [x] If the person challenges the candidate, that is enough to not grant it approval
- [x] After clicking the button, the page with all the listings in our database shows up. If the person downvoted the candidate in the flow above, the candidate did not become a listing, therefore will not be in this page.

Please also note:

1. In the future, we may want to make it so students and university founders can also vote. To be discussed.
1. If a conversation about this issue is happening when it is being worked on (i.e., has an assignee),
the outcomes should be documented here (not in the comments).

### Resources:

Add image here.

**Comment by SUICIDALcow** [comment]
@sofiatti, the page is described as having both an upvote and a downvote button, but only describes what happens when the downvote button is clicked. Also, it sounds like a single downvote will prevent a listing from being whitelisted. Would it make more sense to simply have a “challenge” button that automatically initiates the challenge and casts a vote against the listing? Then any applied listing that is not challenged would be whitelisted after the apply stage timer has elapsed.

**Comment by sofiatti** [comment]
@SUICIDALcow: awesome idea. We can develop that version as a stepping stone. I.e. the “Challenge” button that automatically casts a vote.  

An improved version would be: 

Reviewer A clicks “vote”. Listings w/ thumbs up and thumbs down buttons shows up.

For the next 3 minutes, reviewer B and reviewer C also see those buttons next to the challenged listing. They can also thumbs up and thumbs down. 

At the end of 3 min, a simple majority decides if the listing gets whitelisted or now. Thumbs up and thumbs down buttons go away. 

As a user of the demo, I would like to demonstrate multiple people interacting with Blockchain so that the audience can better understand TCR

As a reviewer, I would like to have an equal weight in deciding which listings get approved so that I can contribute to the quality of the dataset as well as my peers. 

—————

I’ll go ahead and edit the current ask to what you proposed and generate the desired future implementation. (Which we may decide to tag with ‘won’t implement’)
