### ISSUE TITLE
Querying data

### ISSUE THREAD

**Issue by sofiatti** [computablelabs/dapp-universities#7]
**As a** person going through the demo, **I want** to get queried/ sorted data **so that** I can retrieve the top 10 schools.

Prior completion of #4 and #5 is needed.

### Acceptance Criteria
- [x] Add a `show top 10` button to the bottom of the page that returns a list of all universities in the database. 
- [x] If the button is clicked, the university list shows only the top 10 schools and their rankings

Please also note:

1. If a conversation about this issue is happening when it is being worked on (i.e., has an assignee),
the outcomes should be documented here (not in the comments).

### Resources:

Add image here.

**Comment by SUICIDALcow** [comment]
I set this to “Top 5” instead of “Top 10” so we don’t have to load as much data to see this functionality. This is easy to change later if we want it to be a different value.

**Comment by SUICIDALcow** [comment]
@sofiattij, can you verify this functionality and close this task if it is complete?

**Comment by sofiatti** [comment]
@SUICIDALcow, this looks done, so I closed it. Let me know if I should re-open it!
